name: Continuous Integration / Continuous Deployment

concurrency:
  group: production
  cancel-in-progress: true

# invoking condition
on:
  pull_request: # when pull request is invoked, and it closed.
    branches: [ "main" ]
    types: closed
  workflow_dispatch: # trigging in github manually.

    
permissions: # permit only reading the source code in repository.
  contents: read

jobs:
  # Build SpringBoot Application.
  build-docker-image:
    runs-on: self-hosted
    steps: # Grouping the step of running.
    - uses: actions/checkout@v3
    # 1.
    - name: Install JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    # 2.
    - name: Grant execute permission for gradlew using chmod +x
      run: chmod +x ./gradlew

    # 3.
    - name: Build with Gradle
      run: ./gradlew clean build

    # 4.
    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USER }}/benchmark .

    # 5. 
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PW }}

    # 6.
    - name: dockerHub push
      run: docker push ${{ secrets.DOCKERHUB_USER }}/benchmark

  run-docker-image:
    # running this step is depend on previous step.
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      - name: pull image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USER }}/benchmark

      - name: halt container
        run: sudo docker stop benchmark 2>/dev/null || true

      - name: run container using Docker-Compose
        run: sudo docker compose -f /docker/.docker-compose.yml up -d benchmark

      - name: remove old image
        run: sudo docker system prune -f